<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="fbUN" Id="{25c001df-3c7a-452c-a9eb-2f93c0a8c1f9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbUN
VAR_IN_OUT
	testUN : ST_UN;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="fbUN">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>