<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{5bccd5a4-76c6-4984-9be1-ff51995fd275}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	un : ST_UN;
	CMD : E_CMD;
	fbTaskPiotrUN : fbTaskPiotrUN;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[un.Cmd := CMD;

fbTaskPiotrUN(un := un);]]></ST>
    </Implementation>
    <Action Name="Init" Id="{240e2975-4539-4594-8253-c4c38cfa784d}">
      <Implementation>
        <ST><![CDATA[// Tutaj planuje przenieść tą inicjalizację a w samym mainie logikę]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="MAIN">
      <LineId Id="409" Count="0" />
      <LineId Id="408" Count="0" />
      <LineId Id="320" Count="0" />
    </LineIds>
    <LineIds Name="MAIN.Init">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>