<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU" Id="{5c7e5af1-d6a9-4457-9412-da2f08e05228}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU EXTENDS fbEM
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>